### ISSUE TITLE
Just a general question

### ISSUE THREAD

**Issue by ChristianGrete** [denodep/dep#3]
Just for clarification and further understanding: I was playing around with this as I was curious about how to handle dependencies in Deno. As far as I understand, dep does not download and install modules into a project (sub-)directory but instead does create a `pkg.json` manifest file and an import map file called `deps.json`. Modules are then "installed" locally on a machine by Deno’s caching mechanism. Is that right?

**Comment by acathur** [comment]
Yes, you're totally right.
